[project]
name = "from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]
